/**
 * demo-fixtures.ts
 *
 * Static seed data used when VITE_DEMO_MODE=true.
 * Mirrors the shape of real FastAPI response objects so the UI
 * works identically in demo mode and with a live backend.
 *
 * Data is based on Kerala, India geography to match the platform context.
 */

import type { AuthUser, TokenPair } from '@/types/user.types';

// ─── Demo Credentials ─────────────────────────────────────────────────────────
export const DEMO_USERS: Record<
  string,
  { password: string; user: AuthUser; tokens: TokenPair }
> = {
  'dispatcher@trauma.demo': {
    password: 'Demo@1234',
    user: {
      id: 'u-001',
      email: 'dispatcher@trauma.demo',
      full_name: 'Arun Krishnan',
      role: 'DISPATCHER',
      phone: '+91-9876543210',
      hospital_id: null,
      ambulance_id: null,
      is_active: true,
      created_at: '2024-01-15T08:00:00Z',
    },
    tokens: {
      access_token:
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.demo_dispatcher',
      refresh_token: 'demo_refresh_dispatcher',
      token_type: 'bearer',
      expires_in: 3600,
    },
  },
  'admin@trauma.demo': {
    password: 'Admin@1234',
    user: {
      id: 'u-002',
      email: 'admin@trauma.demo',
      full_name: 'Priya Menon',
      role: 'ADMIN',
      phone: '+91-9876543211',
      hospital_id: null,
      ambulance_id: null,
      is_active: true,
      created_at: '2024-01-10T08:00:00Z',
    },
    tokens: {
      access_token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.demo_admin',
      refresh_token: 'demo_refresh_admin',
      token_type: 'bearer',
      expires_in: 3600,
    },
  },
  'hospital@trauma.demo': {
    password: 'Hosp@1234',
    user: {
      id: 'u-003',
      email: 'hospital@trauma.demo',
      full_name: 'Dr. Suresh Pillai',
      role: 'HOSPITAL_STAFF',
      phone: '+91-9876543212',
      hospital_id: 'h-001',
      ambulance_id: null,
      is_active: true,
      created_at: '2024-01-20T08:00:00Z',
    },
    tokens: {
      access_token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.demo_hospital',
      refresh_token: 'demo_refresh_hospital',
      token_type: 'bearer',
      expires_in: 3600,
    },
  },
  'gov@trauma.demo': {
    password: 'Gov@1234',
    user: {
      id: 'u-004',
      email: 'gov@trauma.demo',
      full_name: 'Anitha Nair',
      role: 'GOVERNMENT',
      phone: '+91-9876543213',
      hospital_id: null,
      ambulance_id: null,
      is_active: true,
      created_at: '2024-02-01T08:00:00Z',
    },
    tokens: {
      access_token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.demo_gov',
      refresh_token: 'demo_refresh_gov',
      token_type: 'bearer',
      expires_in: 3600,
    },
  },
};

// ─── Demo Incidents ────────────────────────────────────────────────────────────
export const DEMO_INCIDENTS = [
  {
    id: 'inc-001',
    incident_number: 'TRK-20240312-001',
    status: 'EN_ROUTE',
    severity: 'CRITICAL',
    accident_type: 'ROAD_ACCIDENT',
    latitude: 9.9312,
    longitude: 76.2673,
    address_text: 'MC Road, Kottayam, Kerala',
    district: 'Kottayam',
    patient_count: 2,
    description: 'Head-on collision between truck and passenger car. Two critically injured.',
    is_mci: false,
    golden_hour_met: null,
    dispatched_ambulance_id: 'amb-001',
    receiving_hospital_id: 'h-001',
    reported_by_id: 'u-001',
    created_at: new Date(Date.now() - 18 * 60 * 1000).toISOString(), // 18 min ago
    updated_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: 'inc-002',
    incident_number: 'TRK-20240312-002',
    status: 'ON_SCENE',
    severity: 'SEVERE',
    accident_type: 'FALL',
    latitude: 10.5276,
    longitude: 76.2144,
    address_text: 'Thrissur-Palakkad Highway, Near Wadakkancherry',
    district: 'Thrissur',
    patient_count: 1,
    description: 'Worker fell from scaffolding. Suspected spinal injury.',
    is_mci: false,
    golden_hour_met: null,
    dispatched_ambulance_id: 'amb-003',
    receiving_hospital_id: 'h-002',
    reported_by_id: 'u-001',
    created_at: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: 'inc-003',
    incident_number: 'TRK-20240312-003',
    status: 'REPORTED',
    severity: 'MODERATE',
    accident_type: 'CARDIAC',
    latitude: 8.5241,
    longitude: 76.9366,
    address_text: 'East Fort, Thiruvananthapuram',
    district: 'Thiruvananthapuram',
    patient_count: 1,
    description: 'Cardiac arrest. CPR in progress by bystander.',
    is_mci: false,
    golden_hour_met: null,
    dispatched_ambulance_id: null,
    receiving_hospital_id: null,
    reported_by_id: null,
    created_at: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
  },
  {
    id: 'inc-004',
    incident_number: 'TRK-20240312-004',
    status: 'HOSPITAL_ARRIVED',
    severity: 'SEVERE',
    accident_type: 'ROAD_ACCIDENT',
    latitude: 11.2588,
    longitude: 75.7804,
    address_text: 'Calicut Bypass Road, Kozhikode',
    district: 'Kozhikode',
    patient_count: 3,
    description: 'Three-vehicle pile-up. All patients now at hospital.',
    is_mci: false,
    golden_hour_met: true,
    dispatched_ambulance_id: 'amb-002',
    receiving_hospital_id: 'h-003',
    reported_by_id: 'u-001',
    created_at: new Date(Date.now() - 95 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },
  {
    id: 'inc-005',
    incident_number: 'TRK-20240312-005',
    status: 'DISPATCH_PENDING',
    severity: 'CRITICAL',
    accident_type: 'BURNS',
    latitude: 9.5916,
    longitude: 76.5222,
    address_text: 'KSRTC Bus Stand Road, Changanacherry',
    district: 'Kottayam',
    patient_count: 1,
    description: 'Chemical factory explosion. Patient with 60% burns.',
    is_mci: false,
    golden_hour_met: null,
    dispatched_ambulance_id: null,
    receiving_hospital_id: null,
    reported_by_id: 'u-001',
    created_at: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },
];

// ─── Demo Ambulances ──────────────────────────────────────────────────────────
export const DEMO_AMBULANCES = [
  {
    id: 'amb-001',
    registration_no: 'KL-05-AA-1234',
    ambulance_type: 'ALS',
    status: 'DISPATCHED',
    current_lat: 9.9612,
    current_lon: 76.2873,
    last_location_at: new Date(Date.now() - 30 * 1000).toISOString(),
    district: 'Kottayam',
    is_active: true,
    staging_station_id: 'st-001',
    device_id: 'GPS-KL-001',
  },
  {
    id: 'amb-002',
    registration_no: 'KL-11-BB-5678',
    ambulance_type: 'BLS',
    status: 'AT_HOSPITAL',
    current_lat: 11.2500,
    current_lon: 75.7800,
    last_location_at: new Date(Date.now() - 60 * 1000).toISOString(),
    district: 'Kozhikode',
    is_active: true,
    staging_station_id: 'st-002',
    device_id: 'GPS-KL-002',
  },
  {
    id: 'amb-003',
    registration_no: 'KL-08-CC-9012',
    ambulance_type: 'ALS',
    status: 'ON_SCENE',
    current_lat: 10.5280,
    current_lon: 76.2148,
    last_location_at: new Date(Date.now() - 45 * 1000).toISOString(),
    district: 'Thrissur',
    is_active: true,
    staging_station_id: 'st-003',
    device_id: 'GPS-KL-003',
  },
  {
    id: 'amb-004',
    registration_no: 'KL-02-DD-3456',
    ambulance_type: 'BLS',
    status: 'AVAILABLE',
    current_lat: 8.5000,
    current_lon: 76.9500,
    last_location_at: new Date(Date.now() - 120 * 1000).toISOString(),
    district: 'Thiruvananthapuram',
    is_active: true,
    staging_station_id: 'st-004',
    device_id: 'GPS-KL-004',
  },
  {
    id: 'amb-005',
    registration_no: 'KL-14-EE-7890',
    ambulance_type: 'NICU',
    status: 'AVAILABLE',
    current_lat: 10.8505,
    current_lon: 76.2711,
    last_location_at: new Date(Date.now() - 90 * 1000).toISOString(),
    district: 'Ernakulam',
    is_active: true,
    staging_station_id: 'st-005',
    device_id: 'GPS-KL-005',
  },
  {
    id: 'amb-006',
    registration_no: 'KL-07-FF-2345',
    ambulance_type: 'MFR',
    status: 'MAINTENANCE',
    current_lat: 9.2648,
    current_lon: 76.7870,
    last_location_at: new Date(Date.now() - 6 * 3600 * 1000).toISOString(),
    district: 'Alappuzha',
    is_active: false,
    staging_station_id: null,
    device_id: 'GPS-KL-006',
  },
];

// ─── Demo Hospitals ───────────────────────────────────────────────────────────
export const DEMO_HOSPITALS = [
  {
    id: 'h-001',
    name: 'Medical College Hospital Kottayam',
    latitude: 9.5916,
    longitude: 76.5222,
    address: 'Gandhinagar, Kottayam, Kerala 686008',
    district: 'Kottayam',
    phone: '0481-2597001',
    trauma_level: 'LEVEL_1',
    is_active: true,
    resources: {
      icu_beds_total: 40,
      icu_beds_available: 6,
      ed_capacity_total: 80,
      ed_capacity_current: 54,
      ventilators_total: 20,
      ventilators_available: 4,
      ot_available: true,
      blood_bank_available: true,
      specialist_on_duty: true,
    },
  },
  {
    id: 'h-002',
    name: 'Jubilee Mission Medical College, Thrissur',
    latitude: 10.5276,
    longitude: 76.2144,
    address: 'Perinchery, Thrissur, Kerala 680005',
    district: 'Thrissur',
    phone: '0487-2435501',
    trauma_level: 'LEVEL_2',
    is_active: true,
    resources: {
      icu_beds_total: 24,
      icu_beds_available: 12,
      ed_capacity_total: 50,
      ed_capacity_current: 31,
      ventilators_total: 12,
      ventilators_available: 7,
      ot_available: true,
      blood_bank_available: true,
      specialist_on_duty: false,
    },
  },
  {
    id: 'h-003',
    name: 'Government Medical College, Kozhikode',
    latitude: 11.2500,
    longitude: 75.7800,
    address: 'Medical College Road, Kozhikode, Kerala 673008',
    district: 'Kozhikode',
    phone: '0495-2350216',
    trauma_level: 'LEVEL_1',
    is_active: true,
    resources: {
      icu_beds_total: 60,
      icu_beds_available: 2,
      ed_capacity_total: 100,
      ed_capacity_current: 92,
      ventilators_total: 30,
      ventilators_available: 1,
      ot_available: true,
      blood_bank_available: true,
      specialist_on_duty: true,
    },
  },
  {
    id: 'h-004',
    name: 'SAT Hospital, Thiruvananthapuram',
    latitude: 8.5241,
    longitude: 76.9366,
    address: 'Ulloor, Thiruvananthapuram, Kerala 695011',
    district: 'Thiruvananthapuram',
    phone: '0471-2524650',
    trauma_level: 'LEVEL_1',
    is_active: true,
    resources: {
      icu_beds_total: 50,
      icu_beds_available: 18,
      ed_capacity_total: 90,
      ed_capacity_current: 43,
      ventilators_total: 25,
      ventilators_available: 11,
      ot_available: true,
      blood_bank_available: true,
      specialist_on_duty: true,
    },
  },
];

// ─── Demo Notifications ───────────────────────────────────────────────────────
export const DEMO_NOTIFICATIONS = [
  {
    id: 'notif-001',
    message: 'Response SLA breach: Incident TRK-20240312-003 — No ambulance dispatched in 5 min',
    severity: 'HIGH',
    is_read: false,
    created_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-002',
    message: 'ICU capacity critical: GMC Kozhikode at 97% — only 2 beds available',
    severity: 'HIGH',
    is_read: false,
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-003',
    message: 'Golden hour achieved: Incident TRK-20240312-004 — patient in hospital within 45 min',
    severity: 'LOW',
    is_read: true,
    created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
];

// ─── Demo KPI Data ────────────────────────────────────────────────────────────
export const DEMO_KPI = {
  avg_response_time_sec: 487,          // ~8 min
  golden_hour_compliance_pct: 73.4,
  total_incidents_today: 5,
  active_incidents: 3,
  ambulances_available: 2,
  ambulances_deployed: 3,
  average_dispatch_time_sec: 94,
};

// ─── Demo Black Spots ────────────────────────────────────────────────────────
export const DEMO_BLACKSPOTS = [
  {
    id: 'bs-001',
    name: 'MC Road Kottayam Junction',
    latitude: 9.9312,
    longitude: 76.2673,
    district: 'Kottayam',
    road_name: 'MC Road (NH 183)',
    incident_count: 47,
    risk_score: 8.9,
    description: 'High-speed junction with frequent rear-end collisions.',
  },
  {
    id: 'bs-002',
    name: 'Kalamassery Industrial Area',
    latitude: 10.0551,
    longitude: 76.3109,
    district: 'Ernakulam',
    road_name: 'NH 544',
    incident_count: 32,
    risk_score: 7.2,
    description: 'Heavy vehicle movement causes frequent collisions with two-wheelers.',
  },
  {
    id: 'bs-003',
    name: 'Calicut Beach Road',
    latitude: 11.2588,
    longitude: 75.7804,
    district: 'Kozhikode',
    road_name: 'Beach Road',
    incident_count: 28,
    risk_score: 6.5,
    description: 'Night-time accidents due to poor lighting and pedestrian crossings.',
  },
];
